spring.application.name=demo

spring.security.user.name=Kali
spring.security.user.password=123
server.servlet.session.cookie.same-site=strict

# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.security.oauth2.client.registration.google.client-id=12q9nhgodi33esu15hp7ejnkn8o.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=GweOCSPX-M91jIxzMOTc4UZLeJ1PPPaQJAW3v
spring.security.oauth2.client.registration.google.scope=openid,profile,email
logging.level.org.springframework.security=DEBUG